# Generated by Django 3.1.7 on 2021-11-03 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spirit_category', '0006_auto_20190120_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(blank=True, default=1, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
